apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: demo-helm-harbor
  namespace: demo-helm-harbor
spec:
  interval: 5m0s
  url: https://core.harbor.smartfactoryhost.com/
  secretRef:
    name: harbor-user