apiVersion: v1
kind: Service
metadata:
  name: sfn-test-app
  namespace: demo
spec:
  type: NodePort
  selector:
    app: sfn-test-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

